"""Copy the entries generated by build-icons.js into m-nata/inc/icons.php.

Usage: python patch-icons.py path/to/icons.generated.json
"""
import json
import os
import re
import sys

BACKSLASH = chr(92)
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGET = os.path.join(ROOT, 'm-nata', 'inc', 'icons.php')

icons = json.load(open(sys.argv[1], encoding='utf-8'))
src = open(TARGET, encoding='utf-8', newline='').read()

for name, markup in icons.items():
    # Entries live inside single-quoted PHP strings.
    assert "'" not in markup and BACKSLASH not in markup, name
    pattern = re.compile(r"(\t\t'" + re.escape(name) + r"'\s*=> )'.*?',\n")
    assert pattern.search(src), 'missing entry: ' + name
    src = pattern.sub(lambda m: m.group(1) + "'" + markup + "',\n", src, count=1)

open(TARGET, 'w', encoding='utf-8', newline='').write(src)
print('patched %d icons' % len(icons))
